name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Compile Java backend
      run: mvn clean compile -DskipTests
      
    - name: Run tests
      run: mvn test
      
    - name: Package application
      run: mvn package -DskipTests
      
    - name: Build Docker image
      run: docker build -t smart-clinic-management:latest .
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: smart-clinic-jar
        path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: echo "Deployment would happen here"
